### ISSUE TITLE
Preview not playing?

### ISSUE THREAD

**Issue by appelfriuts** [bunfan/Beat-Banger-Charting-Tool#1]
I have a sprite sheet I set up as a sample to test the mod maker and it's not playing at all, just stays still and is kinda blurry. Even tested with the sprites that come with the game, didnt work. also I can't figure out how to input the BPM. Dunno if it's a bug or if i'm dumb lol

**Comment by kensdentv** [comment]
Are you loading a song and chart before trying to preview the loop?

**Comment by kensdentv** [comment]
Fixed in v 1.22
