### ISSUE TITLE
The Charting Tool does not overwrite the "no_spawn" array when re-charting

### ISSUE THREAD

**Issue by JMVRy** [bunfan/Beat-Banger-Charting-Tool#3]
So, I generate a chart, and it generates fine. When I move a "no_spawn" note forward or back, it duplicates in the chart.

"no_spawn=[ 0, 5, 9, 12, 16, 0, 5, 13, 21, 28 ]"

Before, it only had one 0 in the array. Now, it duplicated the numbers.

**Comment by kensdentv** [comment]
Fixed in v1.2 Thank you <3
